In [103]:
import pandas as pd
import numpy as np

In [104]:
df = pd.read_csv('./dataset/airbnb_seasons_20172018/airbnb_cleaned_fall.csv', encoding='Latin-1')

In [105]:
df['zipcode'] = pd.to_numeric(df['zipcode'], errors='coerce').fillna(0)
df['host_is_superhost'] = pd.to_numeric(df['host_is_superhost'], errors='coerce').fillna(0)

df

Unnamed: 0        id    host_id       scrape_id  zipcode  \
0                0      2515       2758  20180908060534  10026.0   
1                1      2539       2787  20180908060534  11218.0   
2                2      2595       2845  20180908060534  10018.0   
3                3      3330       4177  20180908060534  11206.0   
4                4      3647       4632  20180908060534  10027.0   
5                5      3831       4869  20180908060534  11238.0   
6                6      4484       5688  20180908060534  10009.0   
7                8      5099       7322  20180908060534  10016.0   
8               10      5172       7386  20180908060534  10016.0   
9               11      5178       8967  20180908060534  10019.0   
10              12      5203       7490  20180908060534  10025.0   
11              14      5238       7549  20180908060534  10002.0   
12              15      5295       7702  20180908060534  10025.0   
13              16      5441       7989  20180908060534  10036.0   
14              18      5945       4267  20180908060534  10024.0   
15              19      6021      11528  20180908060534  10025.0   
16              20      6090      11975  20180908060534  10014.0   
17              22      6990      16800  20180908060534  10029.0   
18              23      7036      53179  20180908060534  11218.0   
19              24      7064      17297  20180908060534  11211.0   
20              25      7097      17571  20180908060534  11205.0   
21              27      7322      18946  20180908060534  10011.0   
22              28      7726      20950  20180908060534  11216.0   
23              30      7970      10496  20180908060534  10010.0   
24              32      8025      22486  20180908060534  11217.0   
25              34      8225       2758  20180908060534  10026.0   
26              35      8343      24222  20180908060534  10009.0   
27              36      8477      25137  20180908060534  10001.0   
28              37      8490      25183  20180908060534  11216.0   
29              38      8505      25326  20180908060534  11218.0   
...            ...       ...        ...             ...      ...   
273783      282034  21517904   88956647  20171101012912  11211.0   
273784      282035  16143905    2125221  20171101012912  11249.0   
273785      282036   2466687    8778997  20171101012912  11211.0   
273786      282037   1620225    8619862  20171101012912  11211.0   
273787      282038  21517798   31304940  20171101012912  11249.0   
273788      282039   8148417   23121971  20171101012912  11211.0   
273789      282040  19944880    5350896  20171101012912  11211.0   
273790      282041  15841513    8439929  20171101012912  11211.0   
273791      282042   1332570      82930  20171101012912  11206.0   
273792      282043  20993336   23352422  20171101012912  11206.0   
273793      282044    152819     132701  20171101012912  11211.0   
273794      282045    545949    2684047  20171101012912  11211.0   
273795      282046   7886635   31304940  20171101012912  11249.0   
273796      282047  18288169    1918417  20171101012912  11211.0   
273797      282048  18896112    3197251  20171101012912  11211.0   
273798      282049  20206733   58353872  20171101012912  11249.0   
273799      282050  21386361  154911850  20171101012912  11206.0   
273800      282051     21220      42756  20171101012912  11211.0   
273801      282052  21518687  105737361  20171101012912  11234.0   
273802      282053  21303716   39246569  20171101012912  10704.0   
273803      282054  21535240   93443702  20171101012912  11694.0   
273804      282055  21199422   12609213  20171101012912  11249.0   
273805      282056  21534865  156527502  20171101012912  10550.0   
273806      282057  21491113    1347535  20171101012912  11694.0   
273807      282058  21518757  105737361  20171101012912  11234.0   
273808      282059  21177432   19177308  20171101012912  11207.0   
273809      282060  20886776     936830  20171101012912  10025.0

In [106]:
df['neighbourhood_cleansed'] = df['neighbourhood_cleansed'].replace(' ', '')
df['neighbourhood_cleansed'] = df['neighbourhood_cleansed'].str.replace(r"[\"\',]", '')
df['neighbourhood_cleansed'] = df['neighbourhood_cleansed'].str.replace("-", "")

In [107]:
def LRfindAveragePrice(location):
    return (df[(df.neighbourhood_cleansed == location)])

area = LRfindAveragePrice('eastchester')
df = area
df.head()

Unnamed: 0       id  host_id       scrape_id  zipcode  \
301          328    63610   310670  20180908060534  10475.0   
6547        6800  4082062   310670  20180908060534  10475.0   
6560        6814  4093399   310670  20180908060534  10475.0   
8168        8451  4963237   310670  20180908060534  10475.0   
8169        8452  4963511   310670  20180908060534  10475.0   

     neighbourhood_cleansed  property_type  room_type  accommodates  bedrooms  \
301             eastchester              1       1.00             3       1.0   
6547            eastchester              1       1.01             2       1.0   
6560            eastchester              1       1.01             2       1.0   
8168            eastchester              1       1.00             4       2.0   
8169            eastchester              1       1.00             7       3.0   

      beds  bed_type  price  number_of_reviews  review_scores_rating  \
301    1.0       1.0   99.0                 27                  98.0   
6547   1.0       1.0   68.0                 26                  94.0   
6560   1.0       1.0   69.0                 34                  99.0   
8168   1.0       1.0  155.0                  7                  97.0   
8169   3.0       1.0  199.0                 11                  89.0   

      availability_30  minimum_nights  bathrooms  host_is_superhost  \
301                12               1        1.0                1.0   
6547               25               1        2.0                1.0   
6560               27               1        1.0                1.0   
8168               25               1        1.0                1.0   
8169               23               1        1.0                1.0   

      host_response_rate  
301                100.0  
6547               100.0  
6560               100.0  
8168               100.0  
8169               100.0

# Load SVR 

In [108]:
from sklearn.svm import SVR
svr_lin = SVR(kernel='linear', C=100, gamma=0.1, epsilon=.1)
svr_rbf = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)
svr_poly = SVR(kernel='poly', C=100, gamma='auto', degree=3, epsilon=.1,
               coef0=1)

In [109]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(df[['accommodates', 'beds', 'bedrooms', 'bathrooms', 'bed_type','property_type', 'number_of_reviews', 'review_scores_rating']],
    df['price'], test_size = 0.30, random_state=42)

In [110]:
#accuracy score
svr_lin.fit(xtrain,ytrain)
lin_pred=svr_lin.predict(xtest)
print(svr_lin.score(xtest,ytest))

0.9472295288346563


In [111]:
#cross eval
scores = cross_val_score(svr_lin, xtest, ytest, cv=5)
scores     

array([0.99215123, 0.77787031, 0.89591909, 0.86932041, 0.50501686])

In [112]:
#prediction result
svr_lin.predict([[2, 1, 1, 1, 1, 1, 0, 70]])

array([55.74248554])

# RBF

In [113]:
#accuracy score
svr_rbf.fit(xtrain,ytrain)
rbf_pred=svr_rbf.predict(xtest)
print(svr_rbf.score(xtest,ytest))

0.5995802602620981


In [114]:
#cross eval
scores = cross_val_score(svr_rbf, xtest, ytest, cv=5)
scores     

array([-0.46373648,  0.42421234,  0.06164268,  0.03655211,  0.87011849])

In [115]:
svr_rbf.predict([[2, 1, 1, 1, 1, 1, 0, 70]])

array([116.65451945])

# Poly

In [116]:
svr_poly.fit(xtrain,ytrain)
poly_pred=svr_poly.predict(xtest)
print(svr_poly.score(xtest,ytest))

-22475.672772220387


In [117]:
#cross eval
scores = cross_val_score(svr_poly, xtest, ytest, cv=5)
scores     

array([-1.29906750e+05, -3.14827355e+04, -3.59819915e+07, -3.87639470e+05,
       -6.14259530e+05])

In [118]:
svr_poly.predict([[2, 1, 1, 1, 1, 1, 0, 70]])

array([-82768.39338737])

In [119]:
df_predictors = df[['accommodates', 'beds', 'bedrooms', 'bathrooms', 'bed_type','property_type', 'number_of_reviews', 'review_scores_rating']]
df_target_value = df[['price']]

In [120]:
import statsmodels.api as sm

df_predictors = sm.add_constant(df_predictors)
est = sm.OLS(df_target_value, 
            df_predictors).fit()
print(est.summary())

                            OLS Regression Results                            
Dep. Variable:                  price   R-squared:                       0.953
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     203.3
Date:                Fri, 17 May 2019   Prob (F-statistic):           6.75e-44
Time:                        09:09:27   Log-Likelihood:                -347.97
No. Observations:                  78   AIC:                             711.9
Df Residuals:                      70   BIC:                             730.8
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
accommodates            31.7284 

/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)
